enum_scenes_ph = [
    ("Custom", "Custom", "Custom"),
    ("sea", "Ocean", "0x00"),
    ("sea_minigame", "Ocean Minigame", "0x01"),
    ("sea_fishing", "Fishing", "0x02"),
    ("sea_salvage", "Salvage", "0x03"),
    ("ship", "Ship", "0x04"),
    ("ship_terry", "Terry's Ship", "0x05"),
    ("ship_wonder", "Mystery Ship", "0x06"),
    ("ship_flink", "Fake Link Ship", "0x07"),
    ("ship_fisher", "Fisherman's Ship", "0x08"),
    ("ship_hoho", "Hohos' Ship", "0x09"),
    ("ship_guard", "Guard Ship", "0x0A"),
    ("isle_main", "Main Island", "0x0B"),
    ("isle_pluck", "Courage Island", "0x0C"),
    ("isle_flame", "Fire Island", "0x0D"),
    ("isle_wind", "Wind Island", "0x0E"),
    ("isle_water", "Ice Island", "0x0F"),
    ("isle_power", "Power Island", "0x10"),
    ("isle_wisdom", "Wisdom Island", "0x11"),
    ("isle_wisdom2", "Wisdom Island 2", "0x12"),
    ("isle_torii", "Torii Island", "0x13"),
    ("isle_hidari", "Hidaridai Island", "0x14"),
    ("isle_myou", "Eerie Island", "0x15"),
    ("isle_wizard", "Guru Island", "0x16"),
    ("isle_shrine", "Shrine Island", "0x17"),
    ("isle_small1", "Small Island 1", "0x18"),
    ("isle_small2", "Small Island 2", "0x19"),
    ("isle_small3", "Small Island 3", "0x1A"),
    ("isle_small5", "Small Island 5", "0x1B"),
    ("dngn_flame", "Fire Temple", "0x1C"),
    ("dngn_wind", "Wind Temple", "0x1D"),
    ("dngn_pluck", "Courage Temple", "0x1E"),
    ("dngn_water", "Ice Temple", "0x1F"),
    ("dngn_power", "Power Temple", "0x20"),
    ("dngn_wisdom", "Wisdom Temple", "0x21"),
    ("dngn_wisdom2", "Wisdom Temple 2", "0x22"),
    ("dngn_wisdom3", "Wisdom Temple 3", "0x23"),
    ("dngn_wisdom4", "Wisdom Temple 4", "0x24"),
    ("dngn_main", "Main Dungeon", "0x25"),
    ("dngn_main_f", "Main - Antechamber", "0x26"),
    ("dngn_first", "Tutorial", "0x27"),
    ("dngn_torii", "Torii Dungeon", "0x28"),
    ("dngn_ghost", "Ghost Ship", "0x29"),
    ("boss_wind", "Wind Boss", "0x2A"),
    ("boss_flame", "Fire Boss", "0x2B"),
    ("boss_pluck", "Courage Boss", "0x2C"),
    ("boss_water", "Ice Boss", "0x2D"),
    ("boss_power", "Power Boss", "0x2E"),
    ("boss_wisdom", "Wisdom Boss", "0x2F"),
    ("boss_ghost", "Ghost Boss", "0x30"),
    ("boss_last1", "Last Boss 1", "0x31"),
    ("boss_last2", "Last Boss 2", "0x32"),
    ("boss_last3", "Last Boss 3", "0x33"),
    ("demo_op", "Opening", "0x34"),
    ("demo_title", "Sitting Idle", "0x35"),
    ("demo_end", "Ending", "0x36"),
    ("demo_chase", "Cutscene 26-03", "0x37"),
    ("player_dngn", "Player", "0x3A"),
    ("battle00", "Battle 0", "0x3E"),
    ("battle01", "Battle 1", "0x3F"),
    ("battle02", "Battle 2", "0x40"),
    ("battle03", "Battle 3", "0x41"),
    ("battle04", "Battle 4", "0x42"),
    ("battle05", "Battle 5", "0x43"),
    ("battle06", "Battle 6", "0x44"),
    ("battle07", "Battle 7", "0x45"),
]

enum_scenes_st = [
    ("Custom", "Custom", "Custom"),
    ("t_area0", "Forest Area", "0x04"),
    ("t_area1", "Snow Area", "0x05"),
    ("t_area2", "Water Area", "0x06"),
    ("t_area3", "Fire Area", "0x07"),
    ("t_tutorial", "Train Tutorial", "0x08"),
    ("t_forest", "Lost Woods", "0x09"),
    ("t_smarine", "Ocean Floor", "0x0A"),
    ("t_smount", "Snow Tunnel", "0x0B"),
    ("t_smount2", "Sand Tunnel", "0x0C"),
    ("t_smount3", "Mountain Tunnel", "0x0D"),
    ("t_minigame", "Target Practice", "0x0E"),
    ("t_dark", "Dark World", "0x0F"),
    ("t_eviltrain", "Phantom Train", "0x10"),
    ("t_eviltrain2", "Phantom Train 2", "0x11"),
    ("t_eviltrain3", "Phantom Train 3", "0x12"),
    ("d_main", "Main Tower", "0x13"),
    ("d_main_f", "Main Tower (Exterior)", "0x14"),
    ("d_main_s", "Stairs", "0x15"),
    ("d_main_a", "Altar Demo", "0x16"),
    ("d_main_w", "Vault", "0x17"),
    ("d_tutorial", "Tutorial", "0x18"),
    ("d_forest", "Forest Temple", "0x19"),
    ("d_snow26", "Snow Temple", "0x1A"),
    ("d_water27", "Water Temple", "0x1B"),
    ("d_flame", "Fire Temple", "0x1C"),
    ("d_sand", "Sand Temple", "0x1D"),
    ("b_forest", "Forest Boss", "0x1E"),
    ("b_snow", "Snow Boss", "0x1F"),
    ("b_water", "Water Boss", "0x20"),
    ("b_flame", "Fire Boss", "0x21"),
    ("b_sand", "Sand Boss", "0x22"),
    ("b_deago", "Diego", "0x23"),
    ("b_last1", "Last Boss 1", "0x24"),
    ("b_last2", "Last Boss 2", "0x25"),
    ("b_last22", "Last Session", "0x26"),
    ("b_last23", "Last Boss 23", "0x27"),
    ("f_hyral", "Castle", "0x28"),
    ("f_htown", "Castle Town", "0x29"),
    ("f_forest1", "Forest Town", "0x2A"),
    ("f_snow", "Snow Town", "0x2B"),
    ("f_water", "Water Town", "0x2C"),
    ("f_flame", "Fire Town", "0x2D"),
    ("f_flame5", "Fire Town Station", "0x2E"),
    ("f_first", "Starting Town", "0x2F"),
    ("f_forest2", "Forest Shrine", "0x30"),
    ("f_snow2", "Snow Shrine", "0x31"),
    ("f_water2", "Water Shrine", "0x32"),
    ("f_flame2", "Fire Shrine", "0x33"),
    ("f_sand", "Sand Shrine", "0x34"),
    ("f_tetsuo", "Ferrus", "0x35"),
    ("f_bridge", "Bridge Work", "0x36"),
    ("f_bridge2", "Bridge", "0x37"),
    ("f_forest3", "Forest Depths", "0x38"),
    ("f_water3", "Lone Island", "0x39"),
    ("f_ajito", "Hideout", "0x3A"),
    ("f_ajito2", "Hideout Interior", "0x3B"),
    ("f_flame3", "Target Practice Station", "0x3C"),
    ("f_flame4", "Hidden Fire Town", "0x3D"),
    ("f_rabbit", "Rabbit", "0x3E"),
    ("f_kakushi1", "Hidden 1", "0x3F"),
    ("f_kakushi2", "Hidden 2", "0x40"),
    ("f_kakushi3", "Hidden 3", "0x41"),
    ("f_kakushi4", "Hidden 4", "0x42"),
    ("f_pirate", "Pirates", "0x43"),
    ("f_passenger", "Passenger Car", "0x44"),
    ("f_trnnpc", "Train NPCs", "0x45"),
    ("tekiya00", "Enemy Room 0", "0x46"),
    ("tekiya01", "Enemy Room 1", "0x47"),
    ("tekiya02", "Enemy Room 2", "0x48"),
    ("tekiya03", "Enemy Room 3", "0x49"),
    ("tekiya04", "Enemy Room 4", "0x4A"),
    ("tekiya05", "Enemy Room 5", "0x4B"),
    ("tekiya06", "Enemy Room 6", "0x4C"),
    ("tekiya07", "Enemy Room 7", "0x4D"),
    ("tekiya08", "Enemy Room 8", "0x4E"),
    ("tekiya09", "Enemy Room 9", "0x4F"),
    ("demo_train", "Demo Train", "0x50"),
    ("battle01", "Battle 1", "0x6D"),
    ("battle02", "Battle 2", "0x6E"),
    ("battle03", "Battle 3", "0x6F"),
    ("battle04", "Battle 4", "0x70"),
    ("battle05", "Battle 5", "0x71"),
    ("battle06", "Battle 6", "0x72"),
    ("battle07", "Battle 7", "0x73"),
    ("battle08", "Battle 8", "0x74"),
    ("battle09", "Battle 9", "0x75"),
    ("battle10", "Battle 10", "0x76"),
    ("battle11", "Battle 11", "0x77"),
    ("battle12", "Battle 12", "0x78"),
]
